-- 모든 레코드 조회하기
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;

-- ANIMAL_ID 역순으로 조회하기
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

-- 아픈 동물의 아이디와 이름 조회하기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = "Sick";

-- 젊은 동물 아이디와 이름 아이디순으로 조회하기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != "Aged" ORDER BY ANIMAL_ID;

-- 아이디, 이름, 보호시작일을 이름순으로 정렬하고 이름이 같은 경우는 보호시작일 역순으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME ASC, DATETIME DESC;

-- 상위 1개 조회하기
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;
