-- 이름이 없는 동물의 ID 조회하기, 단 ID 오름차순으로 정렬
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID;

-- 이름이 있는 동물의 ID 조회하기, 단 ID 오름차순으로 정렬
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;

-- 이름이 NULL 이면 "No name"으로 표기하기
SELECT ANIMAL_TYPE, IFNULL(NAME, "No name") AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;